### ISSUE TITLE
WinForms example will no longer run

### ISSUE THREAD

**Issue by atecey** [AdsJumbo/AdsJumbo.com#27]
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for '<Module>' threw an exception.
  Source=AdsJumbo_WinForm_Example
  StackTrace:
   at AdsJumbo_WinForm_Example.Form1..ctor() in D:\Downloads\AdsJumbo.com-master (2)\AdsJumbo.com-master\AdsJumbo_WinForm_Example\AdsJumbo_WinForm_Example\Form1.cs:line 72
   at AdsJumbo_WinForm_Example.Program.Main() in D:\Downloads\AdsJumbo.com-master (2)\AdsJumbo.com-master\AdsJumbo_WinForm_Example\AdsJumbo_WinForm_Example\Program.cs:line 19

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: This copy of 'AdsJumboWinForm' has expired and will no longer run. 
This is because it was created using a version of Red Gate's SmartAssembly which is only licensed for testing software. 

You should report this problem to the vendor who supplied 'AdsJumboWinForm'.

**Comment by adjumbo** [comment]
Hello, Thanks for reporting an issue. The Nuget package will be updated.
